# Configuration File for Password Cracker Project

# enter your config.yaml absolute path
CONFIG_LOCATION: 'C:\\Users\\aviva\\OneDrive\\Desktop\\password_cracker_\\config\\config.yaml'

# Master server configurations
MASTER:
  address: "http://127.0.0.1"
  port: 5000

# minions configurations
NUMBER_OF_MINIONS: 3

# Minion server configurations
MINIONS:
  - address: "http://127.0.0.1"
    port: 5001
  - address: "http://127.0.0.1"
    port: 5002
  - address: "http://127.0.0.1"
    port: 5003

# File and upload configurations
# FORMAT: "C:/Users/your_username/your_project_folder/input_files"
UPLOAD_FOLDER: 'C:\\Users\\aviva\\OneDrive\\Desktop\\password_cracker_\\src\\input_files'
ALLOWED_EXTENSIONS: ["txt"]

# Flask application configurations
FLASK:
  DEBUG: False
  SECRET_KEY: "your_secret_key_here"

# Task-related configurations, cannot be zero.
NUMBER_OF_TASKS: 12

# check status after this amount of iterations
CHECK_STATUS_AFTER: 100000

# number of processes to run concurrently on each task.
SPLIT: 4

